title: OPhasengruppe Pirates
email: bitteschreibmirnicht@gmail.not
url: "http://pirates-ophase.github.io"
logo: "http://www.pirates-ophase.de/wp-content/uploads/2014/10/Banner200px1.jpg"

description: > # this means to ignore newlines until "baseurl:"
  Die OPhasengruppe "Pirates" steht für Spaß und Spannung
  Alkohol ist böse!
  Trinkt Wasser statt Bier!

theme: jekyll-theme-minimal
